server {
    listen 80;
    server_name _;

    root /var/www/local;
    index index.html;

    location /data/ {
        add_header Cache-Control "no-cache";
        add_header Access-Control-Allow-Origin "*";
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
